#!/bin/bash
while true
do
TIME=`date +%T`
PING=`ping $1 -c 2 | grep icmp | grep seq=2`
echo "[$TIME] $PING" >> /root/bin/ping_test.log
echo "[$TIME] $PING"
done

"""
* Предполагается запуск с bush командой nohup - для работы после перезагрузки
   и с & - для работы в фоновом режиме

Tasks:
    1) Переделать в .py
    2) Посмотреть подификации   
    3) Добавить номера строк
    4) добавить опционально в __Init_ping__


"""
